export const API_URL =
  "https://63f71c25e40e087c958797ea.mockapi.io/studentAndTeacher";

const data = {
  students: [
    {
      id: "1",
      pic: "",
      name: "arun",
      rollNum: "21",
      class: "10th",
    },
    {
      id: "2",
      pic: "",
      name: "vijay",
      rollNum: "22",
      class: "10th",
    },
    {
      id: "3",
      pic: "",
      name: "ajith",
      rollNum: "23",
      class: "10th",
    },
    {
      id: "4",
      pic: "",
      name: "kamal",
      rollNum: "24",
      class: "10th",
    },
  ],
  teachers: [
    {
      id: "1",
      pic: "",
      name: "Tonny stark",
      age: "60",
      subject: "Nano Tech",
      experience: "40 Years",
    },
    {
      id: "2",
      pic: "",
      name: "Thor",
      age: "45",
      subject: "Thunder",
      experience: "30 Years",
    },
    {
      id: "3",
      pic: "",
      name: "Brus",
      age: "53",
      subject: "Chemistry",
      experience: "25 Years",
    },
    {
      id: "4",
      pic: "",
      name: "Thanos",
      age: "58",
      subject: "Stones",
      experience: "40 Years",
    },
  ],
};

const data1 = [
  {
    type: "student",
    id: "s1",
    pic: "",
    name: "arun",
    rollNum: "21",
    class: "10th",
  },
  {
    type: "student",
    id: "s2",
    pic: "",
    name: "vijay",
    rollNum: "22",
    class: "10th",
  },
  {
    type: "student",
    id: "s3",
    pic: "",
    name: "ajith",
    rollNum: "23",
    class: "10th",
  },
  {
    type: "student",
    id: "s4",
    pic: "",
    name: "kamal",
    rollNum: "24",
    class: "10th",
  },
  {
    type: "teacher",
    id: "t1",
    pic: "",
    name: "Tonny stark",
    age: "60",
    subject: "Nano Tech",
    experience: "40 Years",
  },
  {
    type: "teacher",
    id: "t2",
    pic: "",
    name: "Thor",
    age: "45",
    subject: "Thunder",
    experience: "30 Years",
  },
  {
    type: "teacher",
    id: "t3",
    pic: "",
    name: "Brus",
    age: "53",
    subject: "Chemistry",
    experience: "25 Years",
  },
  {
    type: "teacher",
    id: "t4",
    pic: "",
    name: "Thanos",
    age: "58",
    subject: "Stones",
    experience: "40 Years",
  },
];
